// Sherwin-Williams Exterior Paint Colors
// Curated selection of popular exterior colors with accurate hex values

const SW_COLORS = [
  // Whites
  { name: "Extra White", code: "SW 7006", hex: "#F1F0E9", category: "white" },
  { name: "Pure White", code: "SW 7005", hex: "#EDECE4", category: "white" },
  { name: "Alabaster", code: "SW 7008", hex: "#EDEADF", category: "white" },
  { name: "Snowbound", code: "SW 7004", hex: "#E8E3D8", category: "white" },
  { name: "Greek Villa", code: "SW 7551", hex: "#F0E6D4", category: "white" },
  { name: "Shoji White", code: "SW 7042", hex: "#E5DFD0", category: "white" },
  { name: "Dover White", code: "SW 6385", hex: "#E7DCC8", category: "white" },
  { name: "Creamy", code: "SW 7012", hex: "#EDE2CC", category: "white" },
  { name: "White Duck", code: "SW 7010", hex: "#E1D9C7", category: "white" },
  { name: "Westhighland White", code: "SW 7566", hex: "#EEE5D3", category: "white" },

  // Grays
  { name: "Repose Gray", code: "SW 7015", hex: "#B8B3A8", category: "gray" },
  { name: "Agreeable Gray", code: "SW 7029", hex: "#CBBFAB", category: "gray" },
  { name: "Mindful Gray", code: "SW 7016", hex: "#ACA89D", category: "gray" },
  { name: "Dorian Gray", code: "SW 7017", hex: "#9F9B90", category: "gray" },
  { name: "Gauntlet Gray", code: "SW 7019", hex: "#807C73", category: "gray" },
  { name: "Anonymous", code: "SW 7046", hex: "#938E83", category: "gray" },
  { name: "Colonnade Gray", code: "SW 7641", hex: "#BDB8AA", category: "gray" },
  { name: "Worldly Gray", code: "SW 7043", hex: "#C7C0AF", category: "gray" },
  { name: "Passive", code: "SW 7064", hex: "#BAB8AF", category: "gray" },
  { name: "Pewter Tankard", code: "SW 0023", hex: "#888580", category: "gray" },
  { name: "Peppercorn", code: "SW 7674", hex: "#585451", category: "gray" },
  { name: "Dovetail", code: "SW 7018", hex: "#908C82", category: "gray" },
  { name: "Mega Greige", code: "SW 7031", hex: "#B1A996", category: "gray" },

  // Beige / Tan
  { name: "Accessible Beige", code: "SW 7036", hex: "#C4B6A1", category: "beige" },
  { name: "Kilim Beige", code: "SW 6106", hex: "#C7B494", category: "beige" },
  { name: "Macadamia", code: "SW 6142", hex: "#C6B499", category: "beige" },
  { name: "Nomadic Desert", code: "SW 6107", hex: "#B8A078", category: "beige" },
  { name: "Latte", code: "SW 6108", hex: "#B09C7E", category: "beige" },
  { name: "Balanced Beige", code: "SW 7037", hex: "#B3A68D", category: "beige" },
  { name: "Sand Dollar", code: "SW 6099", hex: "#D2C2A7", category: "beige" },
  { name: "Whole Wheat", code: "SW 6121", hex: "#B49A74", category: "beige" },
  { name: "Toasty", code: "SW 6095", hex: "#C0A480", category: "beige" },
  { name: "Sanderling", code: "SW 7513", hex: "#C8B79A", category: "beige" },

  // Blues
  { name: "Naval", code: "SW 6244", hex: "#2E3441", category: "blue" },
  { name: "Smoky Blue", code: "SW 7604", hex: "#7A8B8F", category: "blue" },
  { name: "Rainwashed", code: "SW 6211", hex: "#B5C8C4", category: "blue" },
  { name: "Sea Salt", code: "SW 6204", hex: "#C5D1CA", category: "blue" },
  { name: "Waterloo", code: "SW 9141", hex: "#6E7B84", category: "blue" },
  { name: "Distance", code: "SW 6243", hex: "#617380", category: "blue" },
  { name: "Gale Force", code: "SW 7605", hex: "#4E5D64", category: "blue" },
  { name: "Denim", code: "SW 6523", hex: "#4B6080", category: "blue" },
  { name: "Needlepoint Navy", code: "SW 0032", hex: "#3B4252", category: "blue" },
  { name: "Labradorite", code: "SW 7619", hex: "#8B9EA5", category: "blue" },
  { name: "Uncertain Gray", code: "SW 6234", hex: "#A2AEB2", category: "blue" },
  { name: "Refuge", code: "SW 6228", hex: "#708892", category: "blue" },
  { name: "Powder Blue", code: "SW 2861", hex: "#98AFC0", category: "blue" },

  // Greens
  { name: "Evergreen Fog", code: "SW 9130", hex: "#95978B", category: "green" },
  { name: "Pewter Green", code: "SW 6208", hex: "#8B9489", category: "green" },
  { name: "Clary Sage", code: "SW 6178", hex: "#9B9A83", category: "green" },
  { name: "Svelte Sage", code: "SW 6164", hex: "#97977E", category: "green" },
  { name: "Retreat", code: "SW 6207", hex: "#7A897E", category: "green" },
  { name: "Rosemary", code: "SW 6187", hex: "#6B7564", category: "green" },
  { name: "Basil", code: "SW 6194", hex: "#576554", category: "green" },
  { name: "Cascade Green", code: "SW 0066", hex: "#89AA9D", category: "green" },
  { name: "Oyster Bay", code: "SW 6206", hex: "#9DACA2", category: "green" },
  { name: "Succulent", code: "SW 9650", hex: "#8D9B7A", category: "green" },
  { name: "Dried Thyme", code: "SW 6186", hex: "#7C7E60", category: "green" },
  { name: "Rookwood Dark Green", code: "SW 2816", hex: "#4A5440", category: "green" },

  // Reds / Burgundy
  { name: "Brick Dust", code: "SW 0009", hex: "#9B5B4C", category: "red" },
  { name: "Red Bay", code: "SW 6321", hex: "#7E3B3B", category: "red" },
  { name: "Fireweed", code: "SW 6328", hex: "#7B3540", category: "red" },
  { name: "Rookwood Red", code: "SW 2802", hex: "#773F3E", category: "red" },
  { name: "Bolero", code: "SW 7600", hex: "#AD5B53", category: "red" },
  { name: "Rojo Marrojo", code: "SW 9182", hex: "#8B4839", category: "red" },
  { name: "Rustic Red", code: "SW 7593", hex: "#703E3C", category: "red" },
  { name: "Sommelier", code: "SW 7595", hex: "#5D3840", category: "red" },
  { name: "Wild Currant", code: "SW 7583", hex: "#6C3A42", category: "red" },
  { name: "Carnelian", code: "SW 7580", hex: "#A04640", category: "red" },

  // Yellows
  { name: "Friendly Yellow", code: "SW 6680", hex: "#EDD391", category: "yellow" },
  { name: "Butter Up", code: "SW 6681", hex: "#F0D48A", category: "yellow" },
  { name: "Hubbard Squash", code: "SW 0044", hex: "#D6A84B", category: "yellow" },
  { name: "Anjou Pear", code: "SW 6381", hex: "#DDC68E", category: "yellow" },
  { name: "Pale Moss", code: "SW 9027", hex: "#D5CCA1", category: "yellow" },
  { name: "Restrained Gold", code: "SW 6129", hex: "#C4AA71", category: "yellow" },
  { name: "Eastlake Gold", code: "SW 0009", hex: "#C09B49", category: "yellow" },
  { name: "Beeswax", code: "SW 7682", hex: "#E8CF94", category: "yellow" },
  { name: "Venetian Yellow", code: "SW 1666", hex: "#E0C073", category: "yellow" },
  { name: "Honeycomb", code: "SW 6375", hex: "#CF9D42", category: "yellow" },

  // Browns
  { name: "Van Dyke Brown", code: "SW 7041", hex: "#6B5C4F", category: "brown" },
  { name: "Umber", code: "SW 6146", hex: "#786454", category: "brown" },
  { name: "Grizzle Gray", code: "SW 7068", hex: "#7D7162", category: "brown" },
  { name: "Virtual Taupe", code: "SW 7039", hex: "#92867A", category: "brown" },
  { name: "Poised Taupe", code: "SW 6039", hex: "#8A7E73", category: "brown" },
  { name: "Sturdy Brown", code: "SW 6097", hex: "#8D6E52", category: "brown" },
  { name: "Java", code: "SW 6090", hex: "#7A5C46", category: "brown" },
  { name: "Turkish Coffee", code: "SW 6076", hex: "#5A4A3E", category: "brown" },
  { name: "Rookwood Medium Brown", code: "SW 2807", hex: "#6E5439", category: "brown" },
  { name: "Status Bronze", code: "SW 7034", hex: "#998E7D", category: "brown" },

  // Dark / Black
  { name: "Iron Ore", code: "SW 7069", hex: "#4B4844", category: "black" },
  { name: "Tricorn Black", code: "SW 6258", hex: "#2F2E2D", category: "black" },
  { name: "Black Fox", code: "SW 7020", hex: "#504C45", category: "black" },
  { name: "Urbane Bronze", code: "SW 7048", hex: "#5E574C", category: "black" },
  { name: "Thunder Gray", code: "SW 7645", hex: "#545759", category: "black" },
  { name: "Inkwell", code: "SW 6992", hex: "#31363F", category: "black" },
  { name: "Cyberspace", code: "SW 7076", hex: "#454C4F", category: "black" },
  { name: "Dark Night", code: "SW 6237", hex: "#3A4651", category: "black" },
  { name: "Ripe Olive", code: "SW 6209", hex: "#4D5040", category: "black" },
  { name: "Greenblack", code: "SW 6994", hex: "#343833", category: "black" },
];
